from pathlib import Path
import zipfile,hashlib,json
r=Path(__file__).resolve().parents[1]
z=r/'SpectrumSprites_13k.zip'; d=r/'dist/index.html'; rel=r/'dist/release.html'; src=r/'src/index.html'
s=src.read_text(encoding='utf-8'); ds=d.read_text(encoding='utf-8')
def compact(q):return '\n'.join(ln for ln in q.splitlines() if not ln.lstrip().startswith('//')).replace('\t','')
weapons=['SIGNATURE','PRISM ROCKET','BOUNCE ORB','ROPE','STAR CHARGE','CLUSTER','STARFALL','SEEKER','PRISM BURST','SUN LANCE','SHOVE','BLINK']
checks={
 'zip_under_13k': z.stat().st_size<=13312,
 'single_file_release': zipfile.ZipFile(z).namelist()==['index.html'],
 'dist_is_safe_compaction_of_source': compact(s)==ds,
 'release_payload_equals_release_dist': zipfile.ZipFile(z).read('index.html')==rel.read_bytes(),
 'version_020': '<title>Spectrum Sprites 0.20</title>' in s,
 'room_code_alphabet_is_clean': "ABCDEFGHJKLMNPQRSTUVWXYZ23456789" in s and "ABCDEFGHJKLMNPPI*2RSTUVWXYZ23456789" not in s,
 'two_teams_six_sprites': 'for(let i=0;i<6;i++)' in s and 'team=i&1' in s,
 'five_procedural_map_archetypes': 'mapType=rnd()*5|0' in s and all(q in s for q in ['mapType==0','mapType==1','mapType==2','mapType==3']),
 'procedural_map_variation': "let a=R(.8,1.25),b=R(-.7,.7),v=R(.8,1.25)" in s,
 'balanced_multilevel_spawn_search': 'o=rnd()*6|0,d=rnd()<.5?1:5,k=rnd()*3|0' in s and '((i+1>>1)+mapType+k)%3<2' in s and 'q<999' in s and 'P.every(z=>Math.abs(z.x-px)>120)' in s,
 'seeded_spawn_lane_rotation_and_mirror': '((o+i*d)%6)*280' in s and 'dir:px<900?1:-1' in s and 'for(let z of [300,490,680,1120,1310,1500])' not in s,
 'live_destructible_collision': 'holes.push([bx,by,r])' in s and 'function solid(px,py)' in s,
 'live_surface_outline_uses_collision_contour': 'function buildEdge()' in s and 'solid(X,y)*8+solid(X+s,y)*4' in s and 'if(tdirty){buildEdge();tdirty=0}' in s,
 'contour_rebuilds_on_terrain_change': s.count('tdirty=1')>=3 and 'if(cut){holes.push([bx,by,r]);tdirty=1}' in s,
 'wildbloom_updates_live_base_terrain': 'h[z]-=Math.max(0,30-Math.abs(k)*.7)' in s,
 'surface_walker_uses_live_ground': 'gy=ground(nx,p.y)-13,dy=gy-p.y' in s and 'dy<15&&dy>-11' in s,
 'mouse_world_aiming': 'function worldMouse()' in s and 'Math.atan2(m[1]-(p.y-8),Math.abs(m[0]-p.x)||1)' in s,
 'left_mouse_charge_fire': "c.addEventListener('pointerdown'" in s and 'charging=1;power=0' in s and "addEventListener('pointerup'" in s and 'fire()' in s,
 'fullscreen_safe_pointer_release': "addEventListener('pointerup'" in s and "c.addEventListener('pointerup'" not in s and "addEventListener('pointercancel'" in s and "c.addEventListener('pointerdown'" in s,
 'trajectory_guide_reuses_physics': 'arc=weapon==1||weapon==2||weapon==5||weapon==8' in s and 'sp=.8+power*6,vx=Math.cos(aa)*sp*p.dir' in s and 's<180' in s and 'solid(px,py)' in s,
 'audio_autoplay_resume': "ac.state=='suspended'&&ac.resume()" in s,
 'audio_feedback_cues': 'p.flash=12;snd(' in s and "p.on=1;snd(760" in s and "p.on=0;snd(150" in s and "wpop=150;snd(500" in s,
 'right_click_weapon_inventory': "e.button==2" in s and 'inv=!inv' in s and "RMB CLOSE" in s and 'ARMORY CASE' in s,
 'inventory_selects_weapon': 'weapon=i;inv=0;wpop=150;' in s and 'say(i?WN[i]:SN[p.type],36)' in s,
 'no_persistent_full_bottom_arsenal': 'fillRect(78,472,804,68)' not in s and 'wpop>0||charging' in s and 'wpop=0' in s,
 'mouse_wheel_zoom': "c.addEventListener('wheel'" in s and 'zoom=clamp(zoom+' in s and ',1,2.2)' in s,
 'zoom_camera_world_transform': 'x.scale(zoom,zoom)' in s and 'function cClamp(v)' in s and 'function zY()' in s,
 'authored_sprite_rig_and_states': 'function sprite(p){' in s and 'st=p.pose||(p.flash?1:won?7:p.hp<30?6:act&&charging?4' in s and 'wIcon(weapon,pt,' in s,
 'shared_weapon_icon_art': 'function wIcon(i,pt,co)' in s and 'wIcon(i,p.type,' in s,
 'narwhal_round4_reveal': 'round==4&&!narAwake' in s and 'DEATHMATCH — THE SEA UNICORN AWAKENS!' in s,
 'narwhal_reduced_midmatch_cadence': 'narAwake&&(round>=8||!(round%2))' in s,
 'narwhal_four_moves': all(q in s for q in ['UNICORN BREACH!','HORN RUSH!','TIDAL SLAM!','RAINBOW SPOUT!']),
 'narwhal_ui_not_blocked_by_inventory_bar': '!narTurn&&phase!=3&&(wpop>0||charging)' in s,
 'fixed_60hz_simulation': 'step=1e3/60' in s and 'while(acc>=step){update();acc-=step}' in s,
 'simulation_owned_turn_delays': 'function delay(n,a){wait=n;after=a}' in s and 'if(wait&&!--wait)' in s and s.count('setTimeout')<=3, # 1 netT + 2 quick-match pre-match timers; sim turns stay on delay()
 'twelve_weapon_slots': all(w in s for w in weapons) and '%12' in s,
 'extended_ballistic_reach': 'sp=.8+power*6' in s and 'w==2||w==5?.11:.08' in s and 'Math.cos(a+j*.16)*sp*p.dir' in s,
 'finite_team_ammo': 'stock[w]--' in s,
 'battlefield_weapon_crates': 'function dropCrate' in s and "say('FOUND '+WN[b.w])" in s,
 'six_named_signatures': all(q in s for q in ['EMBER FLARE','TIDAL ORB','WILDBLOOM','VOLT TRIDENT','MOON SPLIT','SOLAR SPEAR']),
 'full_world_sky_attacks_clamped': 'x:clamp(target+R(-100,100),5,W-5)' in s,
 'star_charge_escape_phase': 'phase=w==4?4:1' in s and '(!phase||phase==4)' in s,
 'shove_respects_facing': "q.team!=p.team&&!q.dead&&(q.x-p.x)*p.dir>0" in s,
 'central_damage_and_resolution': 'function hurt(' in s and 'function resolve()' in s and 'if(n<0)return resolve()' in s,
 'zopfli_candidate_packer': 'zopfli.zlib.compress' in (r/'tools/pack.py').read_text(encoding='utf-8'),
 'roadroller_pipeline_packer': 'roadroller' in (r/'tools/pack.py').read_text(encoding='utf-8'),
 'offline_first_native_ws': "new WebSocket('wss://relay.js13kgames.com/parties/spectrumsprites/" in s and 'fetch(' not in s and 'import ' not in s,
 'local_start_bypasses_network': 'function localStart(){net=0;started=1' in s,
 'online_deterministic_seed_lockstep': 'seed=seed0;myTeam=isHost?0:1' in s and "wsend('F'+turn+','+active" in s,
 'online_host_authority': 'myTeam=isHost?0:1' in s and "if(isHost)wsend('K'+turn+','+ghash())" in s,
 'cosmetic_shake_off_gameplay_prng': 'sh=shake?(Math.random()*2-1)*shake:0' in s,
 'online_turn_ownership_gate': 'mine=(!net||p&&myTeam==p.team)&&!(aiMode&&p.team==1)' in s and 'mine=(!net||P[active]&&myTeam==P[active].team)&&!(aiMode&&P[active]&&P[active].team==1)' in s,
 'online_state_hash_and_resync': 'function ghash()' in s and 'function snap()' in s and 'function unsnap(' in s,
 'online_movement_is_turn_scoped': "wsend('M'+turn+','+active" in s and "if(+a[0]!=turn||+a[1]!=active)return" in s,
 'online_remote_clock_sync': "+','+clock" in s and 'clock=+a[6]' in s,
 'online_hash_covers_terrain_and_crates': 'JSON.stringify([holes,crates,h,' in s and 'a.charCodeAt()' in s,
 'pinned_build_tools_declared': '"roadroller": "2.1.0"' in (r/'package.json').read_text() and '"terser": "5.50.0"' in (r/'package.json').read_text(),
 'clean_source_first_packer_no_compat': "node_modules'" in (r/'tools/pack.py').read_text() and "terser/bin/terser" in (r/'tools/pack.py').read_text() and "roadroller/cli.mjs" in (r/'tools/pack.py').read_text() and 'patched_base' not in (r/'tools/pack.py').read_text() and 'compat016' not in (r/'tools/pack.py').read_text(),
 'online_disconnect_graceful': "netUI='left'" in s and 'CONTINUE LOCAL' in s,
 # 0.16 cavern flow / structural optimization
 'derived_cavern_flow': 'ch=i=>h[i]+115+(h[(i+99)%W]-h[i])/3' in s and 'Math.abs(py-ch(i))<46' in s,
 'cavern_render_is_continuous_not_bubbles': "x.lineWidth=92" in s and 'x.lineTo(i-cam,ch(i))' in s,
 'natural_caverns_not_serialized_as_holes': 'for(let x=180;x<W-180;x+=88)holes.push' not in s and 'holes.push([bx,by,r])' in s,
 'dynamic_crater_fast_reject': 'if(Math.abs(dx)<a[2])' in s,
 'cave_aware_blink': 'cave=w==11&&p.y>h[p.x|0]+70' in s and 'ground(target,cave?ch(target|0):0)' in s,
 # 0.14 battlefield depth / traversal / balance
 'deeper_world_and_lower_waterline': 'W=1800,H=780,VW=960,VH=540' in s and 'let water=700,ac' in s and 'function init(){water=700;terrain()' in s and 'cam=0;camY=0' in s,
 'procedural_subterranean_layer': 'Math.abs(py-ch(i))<46' in s and "x.strokeStyle='#21142f'" in s,
 'contextual_cavern_flooring': 'function ground(px,from=0)' in s and 'ground(nx,ny+13)' in s and 'ground(q.x,q.y)' in s,
 'vertical_camera_traversal': 'camY=0' in s and 'x.translate(0,-camY)' in s and 'camY+=(clamp(' in s and 'worldMouse(){let y=zY();return [cam+VW/2' in s,
 'rope_is_symmetric_armory_traversal': "'ROPE'" in s and 'else if(w==3){p.dx=Math.cos(a)*p.dir*(3+power*3)' in s and 'stock[w]--' in s,
 'blink_is_symmetric_armory_traversal': "'BLINK'" in s and 'else if(w==11){let fy=ground(target,cave?ch(target|0):0);p.x=target' in s and 'weapon==6||weapon==11' in s,
 'signature_team_raw_damage_balanced': 'bolt(p,3,.03,7,15,pt)' in s and 'life:180,r:5,d:20,g:.1' in s and 'life:110,r:4,d:58,g:0' in s,
 'destruction_strength_preserved': 'pt==1?38:52' in s and 'q.r>8?62:34' in s,
 # 0.13 fairness / online recovery
 'high_arc_ballistics_do_not_burn_life_offscreen': 'if(q.y>=0||!q.g)q.life--' in s,
 'snapshot_preserves_transition_delay': 'u:wait,v:after' in s and 'wait=o.u;after=o.v' in s,
 'snapshot_preserves_narwhal_motion_authority': 'd:narDir' in s and 'x:narTX' in s and 'narDir=o.d' in s and 'narTX=o.x' in s,
 'narwhal_position_synced_on_fire': "+','+narX+','+narDir" in s and 'narX=+a[9];narDir=+a[10]' in s,
 'decisive_packets_are_turn_scoped': s.count('if(+a[0]!=turn||+a[1]!=active)return')>=4 and "wsend('C'+turn+','+active+','+i)" in s,
 'prematch_guest_slot_recovers': "if(isHost&&!started&&id==guestId)guestId=''" in s,
 'extra_guest_gets_room_full_assignment': "else if(id!=guestId)wsend('S'+guestId+'|'+seed0+'|'+myId)" in s,
 'online_hash_covers_narwhal_authority': 'narHP+narStun*7+(narMode+3)*13+narAwake*5' in s and 'narTurn,phase,narTX|0' in s,
 'online_hash_excludes_cosmetic_patrol': 'h,narX|0,narDir,narTurn' not in s,
 'online_gameplay_packets_require_started': 'if(!started)return;// gameplay packets are inert' in s,
 'aim_guide_active_player_only': "!over&&!inv&&(!net||myTeam==P[active].team)){let p=P[active],sx=p.x-cam" in s,
 # 0.11 mechanical corrections
 'bounce_only_off_terrain_direct_hits_resolve': 'q.b&&!hitP&&q.life>20&&q.y<water' in s,
 'narwhal_no_hidden_damage_while_stunned': 'if(narAwake&&!narStun){' in s,
 'bolt_and_sunlance_no_normal_crater': 'q.shot||q.beam?0:1' in s,
 # 0.11 authored visual pass
 'vfx_shared_primitives': 'function splash(sx)' in s and 'a.smoke' in s and 'a.flash' in s and 'smoke:1' in s,
 'water_splashes': 'q.y>=water)splash(q.x)' in s,
 'narwhal_entrance_staging': 'splash(narX)' in s and "snd(78,1,.07,'sawtooth',2.6)" in s,
 'ui_outlined_labels_not_debug_box': 'x.strokeText(lab,sx,sy-44)' in s and 'fillRect(sx-lw/2-3,sy-51' not in s,
 'title_result_composed_with_renderer': s.count('sprite({x:cam+')>=2,
 'terrain_material_crystals': "x.moveTo(0,-s*1.9)" in s,
 # Natural terrain & water pass
 'shared_wave_surface': 'function wsurf(wx)' in s and 'if(narAwake){let d=wx-narX' in s,
 'water_uses_wave_surface_not_bands': 'x.lineTo(sx,wsurf(sx+cam))' in s and "for(let yy=water;yy<VH;yy+=12)" not in s,
 'curved_terrain_following_strata': 'let y=h[i]+20+b*28+Math.sin(i*.006+b*1.7)' in s and "for(let yy=330;yy<560;yy+=28)" not in s,
 'narwhal_floats_on_wave_surface': 'wsurf(narX)-8-lift' in s,
 # Authored UI / menu finalization pass
 'chamfered_panel_helper': 'function chip(px,py,w,h,fill,st,c=5)' in s,
 'authored_hud_modules': 'chip(10,10,150,32' in s and 'SEA UNICORN' in s and "fillText('SPECTRUM SPRITES',16,22)" not in s,
 'title_menu_architecture': "['LOCAL BATTLE','VS COMPUTER','QUICK MATCH','ONLINE HOST','ONLINE JOIN']" in s and 'ENTER / CLICK' in s and 'div id="h"' not in s,
 'title_uses_full_scene_no_black_box': "x.fillRect(150,95,660,350)" not in s,
 'weapon_popup_context_aware': 'TARGET · LMB FIRE' in s and 'RANGE 75 · SHOVE' in s,
 'result_plaque_authored': 'chip(300,150,360,104' in s and "'▶ ENTER · REMATCH'" in s,
 'staged_title_cast_poses': 'pose:poses[i]' in s and 'let poses=[2,2,7,4,5,7]' in s,
 # 0.19 theme pass: unicorns & rainbows
 'sea_unicorn_framing': 'UNICORN STUNNED FOR 2 TURNS!' in s and "'SEA UNICORN'" in s and 'UNICORN STUNNED — ' in s,
 'rainbow_projectile_trails': "x.strokeStyle='hsl('+((q.x*.7+q.y+t*3)%360|0)+',95%,64%)'" in s,
 'victory_confetti': 'if(a||b)for(let i=0;i<36;i++)parts.push({x:cam+250+Math.random()*460' in s,
 'confetti_off_gameplay_prng': 'y:camY-14-Math.random()*130' in s and 'resolve(){let a=teamAlive(0),b=teamAlive(1);if(a&&b)return 0;over=a?1:b?2:3' in s,
 # 0.19 AI opponent
 'ai_opponent_menu_and_gating': "'VS COMPUTER'" in s and '(msel+4)%5' in s and '(msel+1)%5' in s and '!(aiMode&&P[active]&&P[active].team==1)' in s and '!(aiMode&&p.team==1)' in s,
 'ai_plans_with_shared_ballistics': 'gg=w==2?.11:w?.08:.1' in s and 'sp=.8+pw*6' in s and 'if(solid(X,Y))hit=1' in s,
 'ai_local_only': 'function aiStart(){aiMode=1;localStart()}' in s and "startNet(){clearTimeout(netT);netUI='';aiMode=0;" in s,
 'ai_charges_through_normal_fire': 'if(aiMode&&power>=aiPw&&P[active].team==1){charging=0;fire()}' in s and 'if(aiMode&&p.team)delay(40,5)' in s,
 'ai_shove_fallback': 'best.s<10&&sn' in s,
 # 0.19 quick-match PvP
 'quick_match_pool_codes': "function quickMatch(){qm=1;qmTry=0;qmPool=Date.now()/6e4|0;netOpen('QM'+qmPool.toString(36),0)}" in s,
 'quick_match_jitter_host_claim': "if(!started&&netUI=='qwait'){isHost=1;netUI='host';if(lp&&!guestId){guestId=lp;seed0=Math.random()*1e9>>>0;wsend('S'+guestId+'|'+seed0+'|'+myId)}}" in s,
 'quick_match_host_tiebreak': "wsend('S'+guestId+'|'+seed0+'|'+myId)" in s and 'a[0]==myId&&(!isHost||myId>a[2])' in s,
 'quick_match_full_auto_retry': "if(qm&&!started)netOpen('QM'+qmPool.toString(36),0)" in s,
 'quick_match_searching_ui': 'SEARCHING FOR OPPONENT…' in s and 'QUICK MATCH…' in s,
 'quick_match_timeout_retry': "netUI=='qwait'&&++qmTry<3" in s,
 # 0.20 music & polish
 'generative_music_scheduler': "if(mus&&started&&!over&&!(t%14))snd(196*[1,1.5,2,2.25,3,2,1.5,1.8][(t/14|0)%8],.16,.005,'triangle',1.005)" in s,
 'music_mute_toggle': 'if(k==' + "'KeyM')mus=!mus" in s and 'lp=' + "''" + ',mus=1;' in s,
 'music_hint_on_title': 'WHEEL ZOOM · M MUSIC' in s,
 'turn_clock_bar': 'x.fillRect(21,35,128*clamp(clock/1800,0,1),2)' in s,
 'crystal_pulse': 'x.globalAlpha=.3+.2*Math.sin(t*.06+i)' in s,
}
assert all(checks.values()),{k:v for k,v in checks.items() if not v}
out={'passed':True,'checks':checks,'releaseBytes':z.stat().st_size,'freeBytes':13312-z.stat().st_size,'releaseSha256':hashlib.sha256(z.read_bytes()).hexdigest(),'distSha256':hashlib.sha256(d.read_bytes()).hexdigest()}
(r/'evidence').mkdir(exist_ok=True)
(r/'evidence/VERIFY_RECEIPT.json').write_text(json.dumps(out,indent=2)+'\n')
print(json.dumps(out,indent=2))
