import fs from'fs';import vm from'vm';import {fileURLToPath} from'url';
const root=fileURLToPath(new URL('../',import.meta.url));
function ctx(){let x=new Proxy({},{get:(o,k)=>k=='measureText'?s=>({width:String(s).length*8}):k=='createLinearGradient'||k=='createRadialGradient'?()=>({addColorStop(){}}):()=>{},set:()=>1}),c={width:960,height:540,getContext:()=>x,addEventListener(){},getBoundingClientRect:()=>({left:0,top:0,width:960,height:540})},q={document:{querySelector:()=>c,body:{classList:{add(){},remove(){}}}},addEventListener(){},requestAnimationFrame(){},setTimeout(){},clearTimeout(){},console,AudioContext:function(){return new Proxy({currentTime:0,destination:{}},{get:(o,k)=>k in o?o[k]:()=>new Proxy({frequency:{},gain:{},type:''},{get:(a,b)=>b in a?a[b]:()=>{},set:()=>1})})},WebSocket:function(){return{}}};q.webkitAudioContext=q.AudioContext;vm.createContext(q);return q}
function body(file){let h=fs.readFileSync(file,'utf8'),a=h.indexOf('<script>')+8,b=h.indexOf('</script>',a);return h.slice(a,b)}
function packedBody(){let s=body(root+'dist/release.html'),out='',q={eval:x=>{out=x},Function,console};vm.createContext(q);vm.runInContext(s,q,{timeout:20000});return out}
function aliases(names){return names?`let INIT=ot,PS=()=>it,HS=()=>Qe,CH=Je,SOL=je,SEED=v=>Ke=v,MAP=()=>ae,WAT=()=>r,WEAP=v=>R=v,POW=v=>C=v,ACT=v=>A=v,PROJ=()=>I,FIRE=ut,WIND=v=>N=v,PH=x=>E=x;`:`let INIT=init,PS=()=>P,HS=()=>h,CH=ch,SOL=solid,SEED=v=>seed=v,MAP=()=>mapType,WAT=()=>water,WEAP=v=>weapon=v,POW=v=>power=v,ACT=v=>active=v,PROJ=()=>proj,FIRE=fire,WIND=v=>wind=v,PH=v=>phase=v;`}
function stress(src,names,n){let q=ctx(),T=aliases(names),test=`;(()=>{${T}let bad=[],min=1e9,pat=new Set,types=Array.from({length:6},()=>new Set),arch=[0,0,0,0,0],r715;for(let z=1;z<=${n};z++){SEED(z*9973);INIT();let p=PS(),hh=HS(),c=[0,0];arch[MAP()]++;for(let i=0;i<6;i++){let a=p[i],cv=a.y>hh[a.x|0]+70;c[a.team]+=cv;types[i].add(((a.x/280)|0)+':'+cv);if(a.y>=WAT()-20||!SOL(a.x,a.y+14))bad.push([z,'pos',i,a.x,a.y]);for(let j=0;j<i;j++)min=Math.min(min,Math.abs(a.x-p[j].x))}if(c[0]!=2||c[1]!=2)bad.push([z,'layers',...c]);pat.add(p.map(a=>((a.x/280)|0)+','+(a.y>hh[a.x|0]+70)).join('|'));if(z==715)r715=[...c,...p.flatMap(a=>[a.x|0,a.y|0])]};function get(w,ty=0){INIT();ACT(ty);WEAP(w);let p=PS(),a=p[ty];a.x=500;a.y=250;a.dir=1;a.aim=-Math.PI/4;POW(1);WIND(0);PH(0);p.forEach((z,i)=>i!=ty&&(z.dead=1));PROJ().length=0;FIRE();let z=PROJ()[0];if(!z)return null;let dx=z.dx,dy=z.dy,g=z.g,y=0,x=0,j=0;while(j++<500){dy+=g;x+=dx;y+=dy;if(y>=0&&j>2)break}return Math.round(x)}__result={badN:bad.length,bad:bad.slice(0,5),min,patterns:pat.size,typeVar:types.map(x=>x.size),arch,seed715:r715,ranges:{rocket:get(1),orb:get(2),cluster:get(5),burst:get(8),seeker:get(7),ember:get(0,0),moon:get(0,4)}}})()`;vm.runInContext(src+test,q,{timeout:120000});return q.__result}
function samples(src,names,n=1000){let q=ctx(),T=aliases(names),test=`;(()=>{${T}let a=[];for(let z=1;z<=${n};z++){SEED(z*9973);INIT();a.push([MAP(),...PS().flatMap(p=>[p.x,p.y,p.dir,p.team,p.type])])}__sample=a})()`;vm.runInContext(src+test,q,{timeout:60000});return q.__sample}
let rs=body(root+'dist/index.html'),ps=packedBody(),readable=stress(rs,0,10000),packed=stress(ps,1,2000),agreement=JSON.stringify(samples(rs,0))==JSON.stringify(samples(ps,1)),r=readable.ranges,ok=!readable.badN&&!packed.badN&&readable.min>=120&&packed.min>=120&&readable.typeVar.every(x=>x>=10)&&agreement&&r.rocket>=550&&r.orb>=400&&r.cluster>=400&&r.burst>=550&&r.seeker>=700&&r.ember>=450&&r.moon>=400;
let out={passed:ok,readableStress:{seeds:10000,...readable},packedStress:{seeds:2000,badN:packed.badN,min:packed.min,typeVar:packed.typeVar,seed715:packed.seed715},packedAgreementSeeds:1000,packedAgreement:agreement};fs.writeFileSync(root+'evidence/SPAWN_RANGE_RECEIPT.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));if(!ok)process.exit(1)
